Building-Django-2.0-Web-Applications/untitled/news/urls.py
from django.urls import path
from . import  views

app_name = "news"
urlpatterns = [
    path('', views.index,name = 'index') ,
    path('add/',views.add_post, name = 'add'),
    path('save/',views.save_news,name = 'save'),
]

Building-Django-2.0-Web-Applications/untitled/polls/urls.py
from django.urls import path
from . import views

app_name ="polls"
urlpatterns = [
    path('detail/<int:Question_id>',views.detailView,name='detail'),
    path('list/',views.viewlist,name='view_list'),
    path('', views.index,name = "index"),
    path('<int:question_id>',views.vote,name='vote'),
]

Building-Django-2.0-Web-Applications/untitled/untitled/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("polls/",include("polls.urls")),
    path('admin/', admin.site.urls),
    path('news/',include("news.urls")),
]

Building-Django-2.0-Web-Applications/untitled/news/models.py
from django.db import models
from django.utils import timezone 
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=1000,blank=False,null=False)
    content = models.CharField(max_length=1000,blank=False,null=False)
    time_create = models.DateTimeField(default=timezone.datetime.now())

Building-Django-2.0-Web-Applications/untitled/polls/models.py
from django.db import models

# Create your models here.

class Question (models.Model):
    question_text = models.CharField(max_length=200)
    time_pub = models.DateTimeField()


class choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    vote = models.IntegerField(default=0)

Building-Django-2.0-Web-Applications/untitled/news/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','content',)

Building-Django-2.0-Web-Applications/untitled/news/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import PostForm
# Create your views here.

def index(repuest):
    return HttpResponse('hello')

def add_post(request):
    a = PostForm()
    return render(request,'news/add_news.html',{'f' : a})

def save_news(request):
    if request.method=='POST':
        g = PostForm(request.POST)
        if g.is_valid():
            g.save()
            return  HttpResponse('luu ok')
        else:
            return HttpResponse('sai validate')
    else:
        return HttpResponse('khong phai post request')

Building-Django-2.0-Web-Applications/untitled/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Question
# Create your views here.
def index(request):
    myname = "Nguyen Manh Tien"
    taisan = ["dt","tivi"]
    contex = {"name": myname , "taisan": taisan}
    return render(request,"polls/index.html",contex)

def viewlist(request):
    list_question = Question.objects.all()
    context = {"ds_quest": list_question}
    return render(request,"polls/question_list.html",context)

def detailView(request,Question_id):
    q = Question.objects.get(pk=Question_id)
    return render(request,"polls/detail_question.html",{"qs":q})

def vote(request,question_id):
    q = Question.objects.get(pk=question_id)
    try:
        data = request.POST['choice']
        c = q.choice_set.get(pk = data)
    except:
        HttpResponse('khoi khong co choice')
    c.vote = c.vote +1
    c.save()
    return render(request,"polls/resutl.html",{"q":q})

Building-Django-2.0-Web-Applications/untitled/news/templates/news/add_news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'news:save' %} }}"method="post">
    {% csrf_token %}
    <p>{{ f.title }} </p>
    <p>{{ f.content }}</p>
    <input type="submit" value="them du lieu">
</form>
</body>
</html>

Building-Django-2.0-Web-Applications/untitled/polls/templates/polls/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
    <div header >
        <h1>my webside </h1>
    </div>
    <div class="menu">
        <ul>
            <li>link 1</li>
            <li>link 2</li>
            <li>link 3</li>
            <li>link 4</li>
            <li>link 5</li>
        </ul>
    </div>
<div class="content">
{% block content %}

{% endblock %}

{% block content123 %}

{% endblock %}

{% block content1234 %}

{% endblock %}


</div>
</body>
</html>

Building-Django-2.0-Web-Applications/untitled/polls/templates/polls/detail_question.html
{% extends 'polls/base.html' %}

{%  block content123 %}
    {% if qs %}
        <h1>{{ qs.question_text }}</h1>
        <form action="{% url 'polls:vote' qs.id%}" method="post">
        {% csrf_token %}
        <ul>
        {% for item in qs.choice_set.all %}
            <li>
                <input type="radio" value="{{ item.id }}" name="choice">{{  item.choice_text  }}
            </li>
        {% endfor %}
        <p><input type="submit" name="gui" value="gui"></p>
        </ul>
        {% else %}
          <h2 style="color: #ffb769"> khong co du lieu nao het</h2>
        </form>
    {% endif %} 
{%  endblock %}

Building-Django-2.0-Web-Applications/untitled/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content  %}

    <p>minh laaaaaaa {{ name }}</p>
    <h1>taisan</h1>
    <ul>
        {% for item in taisan %}
        <li>tai san cua toi {{ item }}</li>
        {% endfor %}
    </ul>
</head>
<body>

</body>
</html>

{% endblock %}

Building-Django-2.0-Web-Applications/untitled/polls/templates/polls/question_list.html
{% extends 'polls/base.html' %}

{%  block content123 %}
    {% if ds_quest %}
        <ul>
        {% for item in ds_quest %}
            <a href="{% url 'polls:detail' item.id %}"> <p>{{  item.question_text  }}</p></a>
        {% endfor %}
        </ul>
    {% else %}
        <h2 style="color: #ffb769"> khong co du lieu nao het</h2>
    {% endif %} 
{%  endblock %}

Building-Django-2.0-Web-Applications/untitled/polls/templates/polls/resutl.html
{% extends 'polls/base.html' %}

{% block content123 %}
    {% if q %}
        <h1>{{ q.question_text }}</h1>
        <p>ket qua cua cau tra loi</p>
        {% for item in q.choice_set.all%}
            <p>{{ item.choice_text }} : <span style="color: red">{{ item.vote }}</span> </p>
        {% endfor %}
        <a href="{% url 'polls:view_list' %}">chon tiep</a>
    {% endif %}
{% endblock %}